### ISSUE TITLE
Defines should be able to be called through Hiera

### ISSUE THREAD

**Issue by ghoneycutt** [Ericsson/puppet-module-cron#14]
Suggest adding a parameter, `fragments`, to the cron class that use `create_resources()` to create cron::fragment definitions. This is similar to https://github.com/ghoneycutt/puppet-module-types/blob/master/manifests/init.pp

**Comment by Phil-Friderici** [comment]
@ghoneycutt that was integrated with https://github.com/Ericsson/puppet-module-cron/commit/fc3acf812884f2e0960b82f4e6326619292516eb
