### ISSUE TITLE
rename variable names

### ISSUE THREAD

**Issue by Phil-Friderici** [Ericsson/puppet-module-cron#23]
some variable names should be renamed for easier understanding
$enable_cron -> $service_enable
$ensure_state -> $service_ensure

**Comment by ghoneycutt** [comment]
So does https://github.com/Ericsson/puppet-module-cron/commit/28a2cb6a46c6f898fcd38ce73832d1dd0af912bd since you change the API by not allowing previously allowed settings of 'purged' and 'held'.

Suggest making these changes and doing a major version bump

**Comment by Phil-Friderici** [comment]
Actually this commit added a values to the list of allowed values. The readme did promise to much

Old regex: ```validate_re($package_ensure, '^(present)|(absent)$'```
new regex: ```validate_re($package_ensure, '^(present)|(installed)|(absent)$'```

Do you need one of these ?

**Comment by Phil-Friderici** [comment]
work on this in PR https://github.com/Ericsson/puppet-module-cron/pull/30

**Comment by Phil-Friderici** [comment]
merged with https://github.com/Ericsson/puppet-module-cron/commit/d16b4cf67a4929c8a7908ff15e627bc3db8560fb
