### ISSUE TITLE
Tags are meant to be immutable

### ISSUE THREAD

**Issue by ghoneycutt** [Ericsson/puppet-module-cron#37]
I believe the tag changed from v2.0.0 -> 2.0.0

Tags are meant to be immutable so everyone using v2.0.0 would be broken. If you mistakenly created a tag, the best thing would be to checkout it out and create a new tag based on that and push that one.

**Comment by ghoneycutt** [comment]
@Phil-Friderici

**Comment by Phil-Friderici** [comment]
Yes I changed it to 2.0.0 to stay in the same style like before. Sorry I didn't wanted to hit you. Will keep an extra eye on that in the future.

**Comment by ghoneycutt** [comment]
Wasn't a big impact, just wanted to draw your attention to it :>
