### ISSUE TITLE
puppet-module-cron info for SLES10

### ISSUE THREAD

**Issue by kividiot** [Ericsson/puppet-module-cron#4]
SLE[S|D] 10 machines need an empty /etc/cron.deny file or the cron daemon shuts down.

Fixed locally by adding this to hiera for SLE[S|D] machines, it just creates the empty file.

cron::cron_deny_users:

**Comment by Phil-Friderici** [comment]
@kividiot Thanks for the report. This was fixed with https://github.com/Ericsson/puppet-module-cron/commit/83d92d21c729a4fbced90fb59debaa0c09e92fae and is available in master branch.
Will be released with v2.0.0 soon
