### ISSUE TITLE
Publish on Puppet Forge

### ISSUE THREAD

**Issue by walkamongus** [Ericsson/puppet-module-cron#46]
Are there any plans to publish this module on the forge?

**Comment by Phil-Friderici** [comment]
Hi @walkamongus,

sorry for the delayed answer. At the moment there are no plan to publish this on the forge.
May I ask what would be the benefit on your side having it available on the forge ?

Thanks & phile grüße

**Comment by walkamongus** [comment]
Hi @Phil-Friderici ,

This is actually the best module I could find that managed cron in the way I was looking for. Putting it on the Forge would make it easier for others to find. I also saw that Ericsson had some other modules on the Forge already.

**Comment by Phil-Friderici** [comment]
Hi @walkamongus,

thanks for the friendly feedback :)
I've just added it to the forge [1].

phile grüße

[1] https://forge.puppet.com/ericsson/cron
