### ISSUE TITLE
Any plans to update ?  RHEL 7 ?  Puppet 5 ? Puppet 6 ?

### ISSUE THREAD

**Issue by linuxdan** [Ericsson/puppet-module-cron#59]
Please ?

**Comment by walkamongus** [comment]
I'm using this module on RHEL 7 with Puppet 5 and haven't encountered any issues yet.

**Comment by Phil-Friderici** [comment]
@linuxdan: The module got updated to support RHEL7 and Puppet 5/6 with release 2.4.0. Therefore I close this issue. Feel free to re-open if something is missing or not working.
